### ISSUE TITLE
Como coloco pra tocar?

### ISSUE THREAD

**Issue by CleyssonDias** [luixlacrux/spotify-finder#5]
fiz tudo certinho, está tudo funcionando!
só gostaria de saber como colocar pra tocar

**Comment by luixlacrux** [comment]
Hi @CleyssonDias this library is outdated and doesn't support new Spotify Web API versions.

If you want to play a track you will need to look up the `preview_url` field exposed in the track object to more info check the Spotify API reference https://developer.spotify.com/documentation/web-api/reference/#/

Hope this information can be useful for you.
